### ISSUE TITLE
Luis Ortiz (656814) Headshot

### ISSUE THREAD

**Issue by peytonsumpter** [camdenk/mlbplotR#13]
Luis Ortiz (BAM 656814) appears to have the wrong headshot. The headshot is showing a Cardinals player, while this Ortiz never played for the Cardinals organization.

**Comment by peytonsumpter** [comment]
Appreciate it! Gave me a good laugh haha

**Comment by camdenk** [comment]
Should be fixed now. Let me know if you have any issues!
