### ISSUE TITLE
DET and CLE logos not showing

### ISSUE THREAD

**Issue by jacobakaye** [camdenk/mlbplotR#14]
<img width="1440" alt="Screenshot 2024-02-01 at 9 24 35 PM" src="https://github.com/camdenk/mlbplotR/assets/126515518/f3801015-5423-4f32-a7bf-13fdf9b2683f">

Logos not appearing when running sample code

**Comment by camdenk** [comment]
I can't seem to reproduce the error on my machine.

Can you restart your R session, run the code below (just to remove some unnecessary adjustments to the logos and make the reprex simpler), and if the logos still don't show up please supply the output of `sessioninfo::session_info()` in a comment below.
```
# reprex attempt

library(mlbplotR)
library(ggplot2)
library(dplyr)

teams_colors_logos <- mlbplotR::load_mlb_teams() |> 
  dplyr::filter(!team_abbr %in% c("AL", "NL", "MLB")) |> 
  dplyr::mutate(
    a = rep(1:6, 5),
    b = sort(rep(1:5, 6), decreasing = TRUE)
  )


ggplot2::ggplot(teams_colors_logos, aes(x = a, y = b)) +
  mlbplotR::geom_mlb_logos(aes(team_abbr = team_abbr), width = 0.075) +
  ggplot2::geom_label(aes(label = team_abbr), nudge_y = -0.35, alpha = 0.5) +
  ggplot2::theme_void()
```

**Comment by jacobakaye** [comment]
It worked! Thank you!

**Comment by camdenk** [comment]
Glad to hear that worked!
